### ISSUE TITLE
Cannot import exported data

### ISSUE THREAD

**Issue by webfrank** [lf-edge/ekuiper#1616]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 1.8.0
- Hardware configuration (e.g. `lscpu`): macOS
- OS (e.g. `cat /etc/os-release`): 12.6.1
- Others:

**What happened and what you expected to happen**:

I exported a config using REST API /data/export and tried to re-import using /data/import.

I've used curl to export/import the json.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This is the error:
```
ekuiper_1  | 2023/01/20 11:16:19 http: panic serving 172.16.23.3:49947: runtime error: invalid memory address or nil pointer dereference
ekuiper_1  | goroutine 106 [running]:
ekuiper_1  | net/http.(*conn).serve.func1()
ekuiper_1  | 	net/http/server.go:1825 +0xbf
ekuiper_1  | panic({0x18e4920, 0x27619f0})
ekuiper_1  | 	runtime/panic.go:844 +0x258
ekuiper_1  | github.com/lf-edge/ekuiper/internal/server.handleError({0x1c58a28, 0xc000c180e0}, {0x0?, 0x0}, {0x1aa7c7e?, 0xc000060c00?}, {0x1c63418, 0xc000227a40})
ekuiper_1  | 	github.com/lf-edge/ekuiper/internal/server/rest.go:70 +0x7f
ekuiper_1  | github.com/lf-edge/ekuiper/internal/server.configurationImportHandler({0x1c58a28, 0xc000c180e0}, 0xc00027c200)
ekuiper_1  | 	github.com/lf-edge/ekuiper/internal/server/rest.go:789 +0x4ba
ekuiper_1  | net/http.HandlerFunc.ServeHTTP(0xc00027c100?, {0x1c58a28?, 0xc000c180e0?}, 0xc000c068c0?)
ekuiper_1  | 	net/http/server.go:2084 +0x2f
ekuiper_1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000fc6c0, {0x1c58a28, 0xc000c180e0}, 0xc0003c7e00)
ekuiper_1  | 	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
ekuiper_1  | github.com/gorilla/handlers.(*cors).ServeHTTP(0xc00043d170, {0x1c58a28, 0xc000c180e0}, 0xc0003c7e00)
ekuiper_1  | 	github.com/gorilla/handlers@v1.4.2/cors.go:54 +0x370
ekuiper_1  | net/http.serverHandler.ServeHTTP({0x1c55928?}, {0x1c58a28, 0xc000c180e0}, 0xc0003c7e00)
ekuiper_1  | 	net/http/server.go:2916 +0x43b
ekuiper_1  | net/http.(*conn).serve(0xc0004da140, {0x1c599b0, 0xc0005dc180})
ekuiper_1  | 	net/http/server.go:1966 +0x5d7
ekuiper_1  | created by net/http.(*Server).Serve
ekuiper_1  | 	net/http/server.go:3071 +0x4db
```

This is the export:
```
{
    "streams": {
        "netflow": "\n              CREATE STREAM netflow\n              ()\n              WITH (FORMAT=\"json\", CONF_KEY=\"default\", TYPE=\"netflow\", SHARED=\"false\", );\n          "
    },
    "tables": {},
    "rules": {
        "collector": "{\"triggered\":true,\"id\":\"collector\",\"sql\":\"select \\n  env(\\\"tenant\\\") as tenant,\\n  host,\\n  src,\\n  dst,\\n  sport,\\n  dport,\\n  snmp_in,\\n  snmp_out,\\n  sum(bytes) as bytes,\\n  sum(packets) as packets,\\n  count(*) as flows\\nfrom netflow\\nGROUP BY tenant,host,src,dst,sport,dport,snmp_in,snmp_out, TUMBLINGWINDOW(ss, 30)\\nhaving bytes \\u003e 0\",\"actions\":[{\"log\":{\"bufferLength\":1024,\"enableCache\":false,\"format\":\"json\",\"omitIfEmpty\":false,\"runAsync\":false,\"sendSingle\":true}}],\"options\":{\"isEventTime\":false,\"lateTolerance\":1000,\"concurrency\":4,\"bufferLength\":1024,\"sendMetaToSink\":false,\"sendError\":true,\"qos\":1,\"checkpointInterval\":300000,\"restartStrategy\":{\"attempts\":0,\"delay\":1000,\"multiplier\":2,\"maxDelay\":30000,\"jitter\":0.1}}}"
    },
    "nativePlugins": {},
    "portablePlugins": {
        "netflow": "{\"name\":\"netflow\",\"file\":\"file:///kuiper/data/uploads/netflow.zip\",\"shellParas\":[]}"
    },
    "sourceConfig": {
        "netflow": "{\"default\":{\"port\":2055}}"
    },
    "sinkConfig": {},
    "connectionConfig": {},
    "Service": {},
    "Schema": {}
}
```

**Comment by superrxan** [comment]
hi @webfrank 

please show us which api you are using to load the data into ekuiper.

Here is the document to demo how to load data by rest api.
https://ekuiper.org/docs/en/latest/api/restapi/data.html#import-data

Note: if you using the file URI, please make sure ekuiper can touch the file.(in our example, "file": "file:///tmp/a.json" means we need put the txt file in the same machine with ekuiper)
