### ISSUE TITLE
got runtime error when using lateTolerance

### ISSUE THREAD

**Issue by xiaoyanc** [lf-edge/ekuiper#1658]
got error when using lateTolerance:
goroutine 1073 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/lf-edge/ekuiper/pkg/infra.SafeRun.func1()
	github.com/lf-edge/ekuiper/pkg/infra/saferun.go:33 +0x45
panic({0x1669fc0, 0xc0004fc1e0})
	runtime/panic.go:838 +0x207
github.com/lf-edge/ekuiper/internal/topo/node.(*defaultNode).doBroadcast(0xc000b0eb40, {0x16b8280, 0xc000a04f00})
	github.com/lf-edge/ekuiper/internal/topo/node/node.go:122 +0x39f
github.com/lf-edge/ekuiper/internal/topo/node.(*defaultNode).Broadcast(0xc000b0eb40, {0x16b8280?, 0xc000a04f00})
	github.com/lf-edge/ekuiper/internal/topo/node/node.go:110 +0xf4
github.com/lf-edge/ekuiper/internal/topo/node.(*WindowOperator).scan(0xc000b844b0, {0xc000754200, 0x1, 0x8}, 0x186a76c0640, {0x18a2bc0?, 0xc00090b2c0?})
	github.com/lf-edge/ekuiper/internal/topo/node/window_op.go:513 +0x8c5
github.com/lf-edge/ekuiper/internal/topo/node.(*WindowOperator).execEventWindow(0xc000b844b0, {0x18a2bc0, 0xc00090b2c0}, {0x0, 0x0, 0x0}, 0x8eb005?)
	github.com/lf-edge/ekuiper/internal/topo/node/watermark.go:234 +0xc6c
github.com/lf-edge/ekuiper/internal/topo/node.(*WindowOperator).Exec.func1.1()
	github.com/lf-edge/ekuiper/internal/topo/node/window_op.go:143 +0x35
github.com/lf-edge/ekuiper/pkg/infra.SafeRun(0xc000bb5790?)
	github.com/lf-edge/ekuiper/pkg/infra/saferun.go:44 +0x62
github.com/lf-edge/ekuiper/internal/topo/node.(*WindowOperator).Exec.func1()
	github.com/lf-edge/ekuiper/internal/topo/node/window_op.go:142 +0xa5
created by github.com/lf-edge/ekuiper/internal/topo/node.(*WindowOperator).Exec
	github.com/lf-edge/ekuiper/internal/topo/node/window_op.go:141 +0x78a
time="2023-03-02 06:25:48" level=error msg="runtime error: runtime error: index out of range [0] with length 0" file="infra/saferun.go:54" rule=tw_twmodel1_count

test rule:
{
    "id": "tw_twmodel1_count",
    "sql": "SELECT count(p1) as count, window_end() as ts, deviceId, modelId from test-source where modelId = \"twmodel1\" GROUP BY deviceId, TUMBLINGWINDOW(mi, 2)",
    "actions": [
        {
            "mqtt": {
                "sendSingle": true,
                "server": "tcp://xxx:1883",
                "topic": "test-sink"
            }
        }
    ],
    "options": {
        "isEventTime": true,
        "lateTolerance": 0
    }
}

test data:
ts, deviceId, modelId, p1
1677723001001,dev1,twmodel1,1 
1677723001001,dev2,twmodel1,1 
1677723011001,dev1,twmodel1,2
1677723011001,dev2,twmodel1,2
1677723119001,dev1,twmodel1,3
1677723120001,dev1,twmodel1,4
1677723119001,dev2,twmodel1,3
1677723120001,dev2,twmodel1,4
1677723131001,dev1,twmodel1,5
1677723131001,dev2,twmodel1,5
1677723241001,dev1,twmodel1,6
1677723241001,dev2,twmodel1,6

**Comment by xiaoyanc** [comment]
The runtime error can not recur when doing test again.
