### ISSUE TITLE
Race condition at httpserver.createDataServer

### ISSUE THREAD

**Issue by levikobi** [lf-edge/ekuiper#2027]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 
1.10.1
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
os: linux 
arch: amd64
- Others:

**What happened and what you expected to happen**:
Expected the rule to change, but the process panicked.

```
ekuiper  | time="2023-06-26 09:08:16" level=info msg="Close file /tmp/results.txt" file="file/file_writer.go:118" rule=rule1
ekuiper  | time="2023-06-26 09:09:14" level=info msg="Create new file writer for /tmp/results.txt" file="file/file_writer.go:42" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Init rule with options &{IsEventTime:false LateTol:1000 Concurrency:1 BufferLength:1024 SendMetaToSink:false SendError:true Qos:0 CheckpointInterval:300000 Restart:0xc0004f0150 Cron: Duration:}" file="planner/planner.go:44"
ekuiper  | time="2023-06-26 09:10:29" level=error msg="runtime error: <nil>" file="infra/saferun.go:55" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="unary operator 2_project instance 0 cancelling...." file="node/operations.go:157" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="unary operator 2_project instance 0 done, cancelling future items" file="node/operations.go:108" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="source my_stream done" file="node/source_node.go:135" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=error msg="runtime error: <nil>" file="infra/saferun.go:55" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Init rule with options &{IsEventTime:false LateTol:1000 Concurrency:1 BufferLength:1024 SendMetaToSink:false SendError:true Qos:0 CheckpointInterval:300000 Restart:0xc0004f0150 Cron: Duration:}" file="planner/planner.go:44"
ekuiper  | time="2023-06-26 09:10:29" level=info msg="file sink done" file="file/file_sink.go:144" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="sink node file_0 instance 0 done" file="node/sink_node.go:198" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Closing file sink" file="file/file_sink.go:198" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="shutting down http data server..." file="httpserver/data_server.go:106" httppush_connection=0
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Close file /tmp/results.txt" file="file/file_writer.go:118" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Opening stream" file="topo/topo.go:138" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="http data server exiting" file="httpserver/data_server.go:110" httppush_connection=0
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Closing HTTP push source" file="http/httppush_source.go:94" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="open source node my_stream with option &{/api/data  json  httppush false   false  0  }" file="node/source_node.go:73" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="open sink node 1 instances" file="node/sink_node.go:134" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=warning msg="fail to find config key  for source httppush" file="conf/source.go:53"
ekuiper  | time="2023-06-26 09:10:29" level=info msg="open source node with props map[delimiter: format:json key: method:POST], concurrency: 1, bufferLength: 102400" file="node/source_node.go:106" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=error msg="http data server error: http: Server closed" file="httpserver/data_server.go:136" httppush_connection=0
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Start source my_stream instance 0 successfully" file="node/source_node.go:139" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Serving http data server on port http://0.0.0.0:10081" file="httpserver/data_server.go:140" httppush_connection=0
ekuiper  | time="2023-06-26 09:10:29" level=error msg="runtime error: http data server shutdown" file="infra/saferun.go:55" rule=rule1
ekuiper  | time="2023-06-26 09:10:29" level=info msg="Rule rule1 is replaced." file="processor/rule.go:110"
ekuiper  | time="2023-06-26 09:10:29" level=info msg="shutting down http data server..." file="httpserver/data_server.go:106" httppush_connection=0
ekuiper  | time="2023-06-26 09:10:29" level=error msg="http data server error: http: Server closed" file="httpserver/data_server.go:136" httppush_connection=0
ekuiper  | panic: close of closed channel
ekuiper  |
ekuiper  | goroutine 58 [running]:
ekuiper  | github.com/lf-edge/ekuiper/internal/io/http/httpserver.createDataServer.func1()
ekuiper  | 	github.com/lf-edge/ekuiper/internal/io/http/httpserver/data_server.go:137 +0xf8
ekuiper  | created by github.com/lf-edge/ekuiper/internal/io/http/httpserver.createDataServer
ekuiper  | 	github.com/lf-edge/ekuiper/internal/io/http/httpserver/data_server.go:128 +0x38a
ekuiper exited with code 0
```

**How to reproduce it (as minimally and precisely as possible)**:
Created a stream and a rule with file sink. The rule was running. Changed the path of the file sink.
**Anything else we need to know?**:
This does not always happens.

**Comment by ngjaying** [comment]
@xjasonlyu Please take a look
