### ISSUE TITLE
tdengine sink add "fields"  error

### ISSUE THREAD

**Issue by gooker** [lf-edge/ekuiper#2668]
**Environment**:

- eKuiper version (e.g. `1.3.0`): 1.12.4
- Hardware configuration (e.g. `lscpu`):x86_64 
- OS (e.g. `cat /etc/os-release`):rocky9.3
- Others:

**What happened and what you expected to happen**:

如果设置TDengine的动态插入规则,设置了"fields": 则提示失败,不使用fields无问题
```
status: stopped
message: Stopped: runtime error: invalid memory address or nil pointer dereference.
```
```
{
  "tdengine": {
    "host":        "hostname",
    "port":        6030,
    "database":    "dab",
    "table":       "tableName", 
    "tsfieldname": "ts",
    "fields":      ["f1","f2"],
    "sTable":      "myStable",
    "tagFields":   ["f3","f4"]
  }
}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
不确定是配置问题还是程序问题.

**Comment by Yisaer** [comment]
@gooker

Please provide the log in the eKuiper which related to the `invalid memory address or nil pointer dereference.`

**Comment by gooker** [comment]
> @gooker
> 
> Please provide the log in the eKuiper which related to the `invalid memory address or nil pointer dereference.`

```



time="2024-03-05T10:46:53+08:00" level=debug msg="rule tdengine11 origin state: Stopped: canceled manually., sginal: 0" file="server/server.go:353"
time="2024-03-05T10:46:53+08:00" level=debug msg="rule tdengine12 origin state: Stopped: runtime error: invalid memory address or nil pointer dereference., sginal: 0" file="server/server.go:353"
time="2024-03-05T10:46:53+08:00" level=debug msg="rule tdenginezs origin state: Stopped: canceled manually., sginal: 0" file="server/server.go:353"
time="2024-03-05T10:46:54+08:00" level=info msg="Rule tdengine12 is replaced." file="processor/rule.go:111"
time="2024-03-05T10:46:54+08:00" level=info msg="Init rule with options &{Debug:false LogFilename: IsEventTime:false LateTol:1000 Concurrency:1 BufferLength:1024 SendMetaToSink:false SendError:true Qos:0 CheckpointInterval:300000 Restart:0xc0009cccf0 Cron: Duration: CronDatetimeRange:[]}" file="planner/planner.go:44"
time="2024-03-05T10:46:54+08:00" level=warning msg="rule tdengine12 is already stopped" file="rule/ruleState.go:184"
time="2024-03-05T10:46:54+08:00" level=info msg="Init rule with options &{Debug:false LogFilename: IsEventTime:false LateTol:1000 Concurrency:1 BufferLength:1024 SendMetaToSink:false SendError:true Qos:0 CheckpointInterval:300000 Restart:0xc0009cccf0 Cron: Duration: CronDatetimeRange:[]}" file="planner/planner.go:44"
time="2024-03-05T10:46:54+08:00" level=info msg="Opening stream" file="topo/topo.go:183" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="open sink node log_0" file="node/sink_node.go:116" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="open sink node tdengine_0" file="node/sink_node.go:116" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Unary operator 2_project is started" file="node/operations.go:71" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="open source node neuronstream with option &{  json  neuron false   false  0   map[] false false}" file="node/source_node.go:83" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="get conf for neuron with conf key : map[format:json key: url:tcp://127.0.0.1:7081]" file="conf/source.go:62"
time="2024-03-05T10:46:54+08:00" level=info msg="open source node with props map[delimiter: format:json key: url:tcp://127.0.0.1:7081], concurrency: 1, bufferLength: 102400" file="node/source_node.go:126" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="open sink node 1 instances with batchSize%!(EXTRA int=0)" file="node/sink_node.go:140" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Trying to get sink for rule tdengine12 with options map[]\n" file="node/sink_node.go:149" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Successfully get the sink log" file="node/sink_node.go:154" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Now is to open sink for rule tdengine12.\n" file="node/sink_node.go:158" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="Opening func collector" file="collector/func.go:52" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Successfully open sink for rule tdengine12.\n" file="node/sink_node.go:162" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Create prometheus stat manager" file="metric/stats_prom.go:30" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="sink node log_0 instance 0 starts with conf {Concurrency:1 Omitempty:false SendSingle:false DataTemplate: Format:json SchemaId: Delimiter: BufferLength:1024 Fields:[] DataField: BatchSize:0 LingerInterval:0 SinkConf:{MemoryCacheThreshold:1024 MaxDiskCache:1024000 BufferPageSize:256 EnableCache:false ResendInterval:0 CleanCacheAtStop:false ResendAlterQueue:false ResendPriority:0 ResendIndicatorField:}}" file="node/sink_node.go:187" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="open sink node 1 instances with batchSize%!(EXTRA int=0)" file="node/sink_node.go:140" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Trying to get sink for rule tdengine12 with options map[database:ems_v1 fields:[f1 f2] host:127.0.0.1 password:taosdata port:6030 stable:Monitor table:Monitor1 tagFields:[f3 f4] tsfieldname:ts user:root]\n" file="node/sink_node.go:149" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Loading symbol Tdengine" file="native/manager.go:756"
time="2024-03-05T10:46:54+08:00" level=debug msg="Successfully look-up plugin Tdengine" file="native/manager.go:762"
time="2024-03-05T10:46:54+08:00" level=debug msg="Successfully get the sink tdengine" file="node/sink_node.go:154" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Now is to open sink for rule tdengine12.\n" file="node/sink_node.go:158" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Opening tdengine sink" file="ext/tdengine.go:202" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Successfully open sink for rule tdengine12.\n" file="node/sink_node.go:162" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Create prometheus stat manager" file="metric/stats_prom.go:30" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="sink node tdengine_0 instance 0 starts with conf {Concurrency:1 Omitempty:false SendSingle:false DataTemplate: Format:json SchemaId: Delimiter: BufferLength:1024 Fields:[f1 f2] DataField: BatchSize:0 LingerInterval:0 SinkConf:{MemoryCacheThreshold:1024 MaxDiskCache:1024000 BufferPageSize:256 EnableCache:false ResendInterval:0 CleanCacheAtStop:false ResendAlterQueue:false ResendPriority:0 ResendIndicatorField:}}" file="node/sink_node.go:187" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Create prometheus stat manager" file="metric/stats_prom.go:30" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="Create prometheus stat manager" file="metric/stats_prom.go:30" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="Start source neuronstream instance 0 successfully" file="node/source_node.go:159" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="createOrGetConnection for tcp://127.0.0.1:7081" file="neuron/connection.go:61" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="Creating neuron connection for tcp://127.0.0.1:7081" file="neuron/connection.go:64" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="Neuron tcp://127.0.0.1:7081 connected" file="neuron/connection.go:81" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="neuron source receiving loop started" file="neuron/connection.go:154" neuron_connection_url="tcp://127.0.0.1:7081"
time="2024-03-05T10:46:54+08:00" level=info msg="neuron connection is attaching" file="neuron/connection.go:130"
time="2024-03-05T10:46:54+08:00" level=info msg="neuron connection attached" file="neuron/connection.go:128"
time="2024-03-05T10:46:54+08:00" level=debug msg="neuron received message {\"node_name\": \"ZS1\", \"group_name\": \"Monitor\", \"timestamp\": 1709606814255, \"values\": {\"PLC_HeartBeat\": 7624, \"PLC_DevId\": 1, \"PLC_TaskNo\": 0, \"PLC_TaskStatus\": 0, \"PLC_TaskType\": 0, \"PLC_TaskUpdate\": 0, \"PLC_CmdType\": 0, \"PLC_CmdUpdate\": 0, \"PLC_Mode\": 1, \"PLC_AlarmCode\": 2, \"PLC_HaveGoods\": 1, \"PLC_HaveCar\": 1, \"PLC_CurTask\": 0, \"PLC_Layers\": 10, \"PLC_CurLayer\": 1, \"PLC_Height\": 100, \"PLC_Speed\": 0, \"PLC_Idle\": 1, \"PLC_Run\": 0, \"WCS_HeartBeat\": 0, \"WCS_DevId\": 0, \"WCS_TaskNo\": 0, \"WCS_TaskType\": 0, \"WCS_TaskStartSide\": 0, \"WCS_TaskStartLayer\": 0, \"WCS_TaskEndSide\": 0, \"WCS_TaskEndLayer\": 0, \"WCS_TaskUpdate\": 0, \"WCS_CmdType\": 0, \"WCS_CmdUpdate\": 0}, \"errors\": {}, \"metas\": {}}" file="neuron/connection.go:158" neuron_connection_url="tcp://127.0.0.1:7081"
time="2024-03-05T10:46:54+08:00" level=debug msg="memory source broadcast from topic $$neuron_tcp://127.0.0.1:7081 to tdengine12_neuronstream_0 done" file="pubsub/manager.go:137" neuron_connection_url="tcp://127.0.0.1:7081"
time="2024-03-05T10:46:54+08:00" level=debug msg="project plan receive &{neuronstream map[errors:map[] group_name:Monitor metas:map[] node_name:ZS1 timestamp:1.709606814255e+12 values:map[PLC_AlarmCode:2 PLC_CmdType:0 PLC_CmdUpdate:0 PLC_CurLayer:1 PLC_CurTask:0 PLC_DevId:1 PLC_HaveCar:1 PLC_HaveGoods:1 PLC_HeartBeat:7624 PLC_Height:100 PLC_Idle:1 PLC_Layers:10 PLC_Mode:1 PLC_Run:0 PLC_Speed:0 PLC_TaskNo:0 PLC_TaskStatus:0 PLC_TaskType:0 PLC_TaskUpdate:0 WCS_CmdType:0 WCS_CmdUpdate:0 WCS_DevId:0 WCS_HeartBeat:0 WCS_TaskEndLayer:0 WCS_TaskEndSide:0 WCS_TaskNo:0 WCS_TaskStartLayer:0 WCS_TaskStartSide:0 WCS_TaskType:0 WCS_TaskUpdate:0]] 1709606814257 map[topic:$$neuron_tcp://127.0.0.1:7081] {{{0 0} 0 0 {{} 0} {{} 0}} map[] map[]} {0 0} map[]}" file="operator/project_operator.go:54" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="sending data: [map[errors:map[] group_name:Monitor metas:map[] node_name:ZS1 timestamp:1.709606814255e+12 values:map[PLC_AlarmCode:2 PLC_CmdType:0 PLC_CmdUpdate:0 PLC_CurLayer:1 PLC_CurTask:0 PLC_DevId:1 PLC_HaveCar:1 PLC_HaveGoods:1 PLC_HeartBeat:7624 PLC_Height:100 PLC_Idle:1 PLC_Layers:10 PLC_Mode:1 PLC_Run:0 PLC_Speed:0 PLC_TaskNo:0 PLC_TaskStatus:0 PLC_TaskType:0 PLC_TaskUpdate:0 WCS_CmdType:0 WCS_CmdUpdate:0 WCS_DevId:0 WCS_HeartBeat:0 WCS_TaskEndLayer:0 WCS_TaskEndSide:0 WCS_TaskNo:0 WCS_TaskStartLayer:0 WCS_TaskStartSide:0 WCS_TaskType:0 WCS_TaskUpdate:0]]]" file="node/sink_node.go:250" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=debug msg="tdengine sink receive [map[errors:map[] group_name:Monitor metas:map[] node_name:ZS1 timestamp:%!s(float64=1.709606814255e+12) values:map[PLC_AlarmCode:%!s(float64=2) PLC_CmdType:%!s(float64=0) PLC_CmdUpdate:%!s(float64=0) PLC_CurLayer:%!s(float64=1) PLC_CurTask:%!s(float64=0) PLC_DevId:%!s(float64=1) PLC_HaveCar:%!s(float64=1) PLC_HaveGoods:%!s(float64=1) PLC_HeartBeat:%!s(float64=7624) PLC_Height:%!s(float64=100) PLC_Idle:%!s(float64=1) PLC_Layers:%!s(float64=10) PLC_Mode:%!s(float64=1) PLC_Run:%!s(float64=0) PLC_Speed:%!s(float64=0) PLC_TaskNo:%!s(float64=0) PLC_TaskStatus:%!s(float64=0) PLC_TaskType:%!s(float64=0) PLC_TaskUpdate:%!s(float64=0) WCS_CmdType:%!s(float64=0) WCS_CmdUpdate:%!s(float64=0) WCS_DevId:%!s(float64=0) WCS_HeartBeat:%!s(float64=0) WCS_TaskEndLayer:%!s(float64=0) WCS_TaskEndSide:%!s(float64=0) WCS_TaskNo:%!s(float64=0) WCS_TaskStartLayer:%!s(float64=0) WCS_TaskStartSide:%!s(float64=0) WCS_TaskType:%!s(float64=0) WCS_TaskUpdate:%!s(float64=0)]]]" file="ext/tdengine.go:208" rule=tdengine12
goroutine 78 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x13
github.com/lf-edge/ekuiper/pkg/infra.SafeRun.func1()
        github.com/lf-edge/ekuiper/pkg/infra/saferun.go:34 +0x3d
panic({0x19723e0?, 0x2690020?})
        runtime/panic.go:914 +0x21f
github.com/lf-edge/ekuiper/extensions/sinks/tdengine/ext.(*taosConfig).buildSql(0xc000212690, {0x1d00ea8, 0xc0008f5080}, 0xc00165f800)
        github.com/lf-edge/ekuiper/extensions/sinks/tdengine/ext/tdengine.go:112 +0x136b
github.com/lf-edge/ekuiper/extensions/sinks/tdengine/ext.(*taosSink).Collect(0xc000147f60, {0x1d00ea8, 0xc0008f5080?}, {0x18c1520?, 0xc001541bd8})
        github.com/lf-edge/ekuiper/extensions/sinks/tdengine/ext/tdengine.go:232 +0x65e
github.com/lf-edge/ekuiper/internal/topo/node.sendDataToSink({0x1d00ea8, 0xc0008f5080}, {0x7ffaff76cf70?, 0xc000147f60?}, {0x18c1520?, 0xc001541bd8?}, {0x1cf59a0, 0xc0000015c0})
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:527 +0x55
github.com/lf-edge/ekuiper/internal/topo/node.doCollectData({0x1d00ea8, 0xc0008f5080}, {0x7ffaff76cf70, 0xc000147f60}, {0x18c1520, 0xc001541bd8}, {0x1cf59a0, 0xc0000015c0}, 0x0)
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:521 +0x114
github.com/lf-edge/ekuiper/internal/topo/node.doCollectMaps({0x1d00ea8, 0xc0008f5080}, {0x7ffaff76cf70, 0xc000147f60}, 0xc001704120?, {0xc0004b1ae8?, 0x0?, 0xc0008a5a88?}, {0x1cf59a0, 0xc0000015c0}, ...)
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:465 +0xba
github.com/lf-edge/ekuiper/internal/topo/node.(*SinkNode).Open.func1.1.1.1.2({0xc0004b1ae8, 0x1, 0x1})
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:251 +0x206
github.com/lf-edge/ekuiper/internal/topo/node.(*SinkNode).Open.func1.1.1.1()
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:313 +0xcdf
github.com/lf-edge/ekuiper/pkg/infra.SafeRun(0xc00038dba0?)
        github.com/lf-edge/ekuiper/pkg/infra/saferun.go:45 +0x57
github.com/lf-edge/ekuiper/internal/topo/node.(*SinkNode).Open.func1.1.1(0xc0005b5e30?)
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:143 +0x85
created by github.com/lf-edge/ekuiper/internal/topo/node.(*SinkNode).Open.func1.1 in goroutine 104
        github.com/lf-edge/ekuiper/internal/topo/node/sink_node.go:142 +0x457
time="2024-03-05T10:46:54+08:00" level=error msg="runtime error: runtime error: invalid memory address or nil pointer dereference" file="infra/saferun.go:56" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=error msg="closing rule tdengine12 for error: runtime error: invalid memory address or nil pointer dereference" file="rule/ruleState.go:214"
time="2024-03-05T10:46:54+08:00" level=info msg="unary operator 2_project instance 0 cancelling...." file="node/operations.go:167" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="unary operator 2_project instance 0 done, cancelling future items" file="node/operations.go:108" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="source neuronstream done" file="node/source_node.go:155" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="closeConnection tcp://127.0.0.1:7081" file="neuron/connection.go:92" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="closing neuron source" file="neuron/source.go:71" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="neuron connection closed, exit receiving loop" file="neuron/connection.go:167" neuron_connection_url="tcp://127.0.0.1:7081"
time="2024-03-05T10:46:54+08:00" level=warning msg="neuron connection detached" file="neuron/connection.go:133"
time="2024-03-05T10:46:54+08:00" level=debug msg="sending data: [map[errors:map[] group_name:Monitor metas:map[] node_name:ZS1 timestamp:1.709606814255e+12 values:map[PLC_AlarmCode:2 PLC_CmdType:0 PLC_CmdUpdate:0 PLC_CurLayer:1 PLC_CurTask:0 PLC_DevId:1 PLC_HaveCar:1 PLC_HaveGoods:1 PLC_HeartBeat:7624 PLC_Height:100 PLC_Idle:1 PLC_Layers:10 PLC_Mode:1 PLC_Run:0 PLC_Speed:0 PLC_TaskNo:0 PLC_TaskStatus:0 PLC_TaskType:0 PLC_TaskUpdate:0 WCS_CmdType:0 WCS_CmdUpdate:0 WCS_DevId:0 WCS_HeartBeat:0 WCS_TaskEndLayer:0 WCS_TaskEndSide:0 WCS_TaskNo:0 WCS_TaskStartLayer:0 WCS_TaskStartSide:0 WCS_TaskType:0 WCS_TaskUpdate:0]]]" file="node/sink_node.go:250" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="sink node log_0 instance 0 stops data resending" file="node/sink_node.go:515" rule=tdengine12
time="2024-03-05T10:46:54+08:00" level=info msg="sink node log_0 instance 0 done" file="node/sink_node.go:301" rule=tdengine12
time="2024-03-05T10:47:03+08:00" level=debug msg="rule tdengine11 origin state: Stopped: canceled manually., sginal: 0" file="server/server.go:353"
time="2024-03-05T10:47:03+08:00" level=debug msg="rule tdengine12 origin state: Stopped: runtime error: invalid memory address or nil pointer dereference., sginal: 0" file="server/server.go:353"
time="2024-03-05T10:47:03+08:00" level=debug msg="rule tdenginezs origin state: Stopped: canceled manually., sginal: 0" file="server/server.go:353"
```

**Comment by Yisaer** [comment]
@gooker

Thanks for your response. Could you also provide the value you send into the stream so that we can reproduce the error.

**Comment by gooker** [comment]
@Yisaer neuron采集的modbustcp数据,
```
kuiper > select * from neuronstream
Query was submit successfully.
kuiper > [{"errors":{},"group_name":"Monitor","metas":{},"node_name":"ZS1","timestamp":1709607567555,"values":{"PLC_AlarmCode":2,"PLC_CmdType":0,"PLC_CmdUpdate":0,"PLC_CurLayer":1,"PLC_CurTask":0,"PLC_DevId":1,"PLC_HaveCar":1,"PLC_HaveGoods":1,"PLC_HeartBeat":8376,"PLC_Height":100,"PLC_Idle":1,"PLC_Layers":10,"PLC_Mode":1,"PLC_Run":0,"PLC_Speed":0,"PLC_TaskNo":0,"PLC_TaskStatus":0,"PLC_TaskType":0,"PLC_TaskUpdate":0,"WCS_CmdType":0,"WCS_CmdUpdate":0,"WCS_DevId":0,"WCS_HeartBeat":0,"WCS_TaskEndLayer":0,"WCS_TaskEndSide":0,"WCS_TaskNo":0,"WCS_TaskStartLayer":0,"WCS_TaskStartSide":0,"WCS_TaskType":0,"WCS_TaskUpdate":0}}]
```

**Comment by Yisaer** [comment]
@gooker 

Can you also provide the rule? I didn't find the `f1`/`f2`/`f3`/`f4` in your value.

**Comment by gooker** [comment]
@Yisaer 好像是配置的事,我的数据源里面select出来的里面没有这个fields对应的貌似值就会这样,我再试试 回头再更新

**Comment by gooker** [comment]
@Yisaer 我简化了一些数据
```
kuiper > select * from neuronstream
Query was submit successfully.
kuiper > [{"errors":{},"group_name":"Monitor","metas":{},"node_name":"ZS1","timestamp":1709610073955,"values":{"PLC_DevId":1,"PLC_HeartBeat":10879,"PLC_TaskNo":0}}]
```

成功的rules

```
{"id": "tdengine","sql": "SELECT group_name,node_name,values->PLC_HeartBeat as PLC_HeartBeat,values->PLC_DevId as PLC_DevId,values->PLC_TaskNo as PLC_TaskNo  from neuronstream ", "actions": [ { "log": { }, "tdengine": { "host": "127.0.0.1", "port": 6030, "user": "root", "password": "taosdata", "database": "zs_v1", "table": "Monitor1", "stable": "Monitor", "tsfieldname": "ts",  "fields":      ["PLC_HeartBeat", "PLC_TaskNo","PLC_DevId"],"tagFields": ["PLC_DevId","PLC_DevId"]} } ] }
```

不成功的rules就是把tagfields设置成group_name","node_name",提示 
> io error: [0x216] syntax error near '>,<nil>) values (now,12000,0,1);' () expected)
```
{"id": "tdengine","sql": "SELECT group_name,node_name,values->PLC_HeartBeat as PLC_HeartBeat,values->PLC_DevId as PLC_DevId,values->PLC_TaskNo as PLC_TaskNo  from neuronstream ", "actions": [ { "log": { }, "tdengine": { "host": "127.0.0.1", "port": 6030, "user": "root", "password": "taosdata", "database": "zs_v1", "table": "Monitor1", "stable": "Monitor", "tsfieldname": "ts",  "fields":      ["PLC_HeartBeat", "PLC_TaskNo","PLC_DevId"],"tagFields": ["group_name","node_name"]} } ] }
```

**Comment by gooker** [comment]
@Yisaer 看了一下TDengine插件的代码 sqlbuild函数里面 tm, _, err := transform.TransItem(item, m.conf.DataField, m.conf.Fields) 这个转换的时候 没有将tagfields的数据放到tm里, 我的理解 Fields存的是要插入到数据库表的对应列里,tagfields是不写入表列而是插入到tags里. 所以tagfields的tags不会放入Fields,原程序里面取tags数据的时候就取不到变成nil, 我测试把tagfields也加入tm就可以了.
